### ISSUE TITLE
Codegen3.7B cannot be loaded

### ISSUE THREAD

**Issue by brutalsavage** [salesforce/CodeGen2#1]
Hi all,

It seems that the 3.7B version of the Codegen2 model cannot be loaded (tried 1B and 7B version and it works fine)

Minimum code to reproduce:
```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen2-3.7B")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen2-3.7B", trust_remote_code=True, revision="main")
```
Error message:
`ModuleNotFoundError: No module named 'transformers_modules.Salesforce.codegen2-3'`

I tried with both latest release and current development of transformers library.

Thanks

**Comment by rooa** [comment]
Great catch, thanks for trying out and letting us know the error! It seems like the "." in repo name was not good. I have updated; could you kindly try the following?:

```python
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen2-3_7B")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen2-3_7B", trust_remote_code=True, revision="main")
```

**Comment by brutalsavage** [comment]
Work now! Thanks for the fast response and great work!
